version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rick-and-morty-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/rickmorty

  mongo-restore:
    image: mongo
    depends_on:
      - mongo
    volumes:
      - /home/ec2-user/containers/instances/rick-and-morty-api/test/data:/data
    command: >
      sh -c "echo 'Restoring data...'; 
             mongorestore --uri mongodb://mongo:27017/rickmorty --drop --dir=/data;
             echo 'Restore complete.'"
    networks:
      - default

volumes:
  mongo-data: