name: "2 - Deploy Infrastructure | TF Apply"

on:
#  schedule:
#    - cron: '30 21 * * 0' # Build infrastructure at 09:30PM UTC Sunday night, 04:30PM EST Sunday Night)
                          # // Note: GitHub Scheduled Actions run ~around the time you schedule.
                          # // It is not uncommon for the start time to be 1-3 hours after the scheduled time.
  push:
    branches:
      - main
    paths-ignore: 
      - '**/*.md'
      - '.github/workflows/**'
      - 'images/**'
      - 'docs/**'
  workflow_dispatch:
  
env:
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  CONFIG_DIRECTORY: "./"
  COMPOSE_REPLACE: leavethisasis
  INSTANCE_CONTAINERS: "containers/instances/"
  K8S_CONTAINERS: "containers/k8s/"

jobs:

  terraform-apply:
    name: Terraform Cloud
    uses: ./.github/workflows/ruw-terraform-apply.yml
    secrets: inherit